name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Build & Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # jeśli masz plik requirements.txt:
          pip install -r requirements.txt

      - name: Smoke test HelloWorld
        run: |
          python HelloWorldProgram/HelloWorldProgram/HelloWorldProgram.py <<< $'Jan\nWarszawa\n'

  cd:
    name: Deploy to AWS Elastic Beanstalk
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Install EB CLI
        run: pip install awsebcli

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init helloworld-app --platform python-3.11 --region ${{ secrets.AWS_REGION }}
          eb deploy Helloworld-app-env

